name: Deploy Image Pixel Sorter static site

on:
  push:
    branches:
      - main

jobs:
  deploy:
    uses: jothamteshome/infra-hub/.github/workflows/deploy-static-site.yml@deploy-static-site-latest
    permissions:
      id-token: write
      contents: read
    secrets:
      AWS_STATIC_SITE_ROLE_TO_ASSUME: ${{ secrets.AWS_STATIC_SITE_ROLE_TO_ASSUME }}
      HOSTED_ZONE_NAME: ${{ secrets.HOSTED_ZONE_NAME }}
      HOSTED_ZONE_ID: ${{ secrets.HOSTED_ZONE_ID }}